### ISSUE TITLE
Professional certification

### ISSUE THREAD

**Issue by vishalkandunuri2** [KaShiekzmi/Coursera-IBM-Full-Stack-Software-Developer-Professional-Certificate#1]
I have completed all the 12 courses. Now what should I do to get the final certificate.

**Comment by KaShiekzmi** [comment]
If you have already paid to Coursera, after completing all prerequisite courses for Specialization Coursera, Coursera will immediately add Specialization Certificate to your list of accomplishments on your profile. You can check your certificate there. Additionally, a specialisation certificate will be mailed to your listed Gmail address. If it's still unavailable, get in touch with the Coursera staff for assistance.
